FROM alpine:3.24 AS gh-installer
ARG GH_VERSION=2.52.0
RUN apk add --no-cache curl tar && \
    ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/') && \
    curl -fsSL "https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_${ARCH}.tar.gz" | \
    tar -xz -C /tmp && \
    cp "/tmp/gh_${GH_VERSION}_linux_${ARCH}/bin/gh" /usr/local/bin/gh

FROM ghcr.io/zeroclaw-labs/zeroclaw:debian
COPY --from=gh-installer /usr/local/bin/gh /usr/local/bin/gh
